In [1]:
import zipfile
import os
import pandas as pd
import numpy as np

In [2]:

# zip_path = "train.zip"      # путь к архиву
# extract_dir = "./"  # куда распаковать

# # создаём папку, если нет
# os.makedirs(extract_dir, exist_ok=True)

# # открываем и извлекаем
# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_dir)

# print(f"✅ Архив {zip_path} успешно распакован в {extract_dir}")

In [3]:


# zip_path = "test.zip"      # путь к архиву
# extract_dir = "./"  # куда распаковать

# # создаём папку, если нет
# os.makedirs(extract_dir, exist_ok=True)

# # открываем и извлекаем
# with zipfile.ZipFile(zip_path, 'r') as zip_ref:
#     zip_ref.extractall(extract_dir)

# print(f"✅ Архив {zip_path} успешно распакован в {extract_dir}")

In [4]:
import pandas as pd

pd.set_option('display.max_rows', 1000)      # показывать все строки
pd.set_option('display.max_columns', 1000)   # показывать все столбцы

In [5]:

train_data = pd.DataFrame(pd.read_csv("train.csv"))
test_data = pd.DataFrame(pd.read_csv("test.csv"))

In [6]:
# train_data.head()

In [7]:
# print(train_data.head())

In [8]:
train_data['price_target'] = np.log10(train_data['price_target'])
print(train_data['price_target'][:10])
train_data.rename(columns = {'price_target': 'square_price_target'}, inplace=True)
train_data['price_target'] = train_data['square_price_target'] * train_data['square'] 
# Комментарий: ВАЖНОЕ ПРЕОБРАЗОВАНИЕ! Логарифмирование целевой переменной по основанию 10. 
# Это стандартный прием для задач регрессии с большим разбросом данных, помогает модели лучше обучаться

0    4.398362
1    4.266639
2    4.241572
3    4.230938
4    4.233818
5    4.601291
6    4.854542
7    4.257220
8    4.307874
9    4.573101
Name: price_target, dtype: float64

In [9]:
train_data['square']

0         78.44
1         34.15
2         59.85
3         67.53
4         58.13
          ...
93450     44.89
93451     29.63
93452     30.00
93453    108.63
93454     57.34
Name: square, Length: 93455, dtype: float64

In [10]:
print(train_data['price_target'] )

0        345.007509
1        145.705705
2        253.858068
3        285.715216
4        246.111845
            ...
93450    200.045918
93451    129.554230
93452    127.025304
93453    505.500994
93454    244.146999
Name: price_target, Length: 93455, dtype: float64

In [11]:
# print(train_data.groupby("hc_name_cat")['price_target'].first())

# Комментарий: Закомментированный анализ цен по категориям недвижимости

In [12]:
# val_data = train_data[:10]

# Комментарий: Закомментированное создание маленькой валидационной выборки

In [13]:
price_mean_hc = train_data.groupby("hc_name_cat")['price_target'].mean().reset_index()

print("1")

train_data = train_data.merge(
    price_mean_hc,
    on = "hc_name_cat",
    how="left",
    suffixes=('_left', '_right')
)
#train_data.head(30)
train_data.rename(columns={"price_target_left": 'price_target', 'price_target_right': 'hc_cat_mean_price'}, inplace=True)

# Комментарий: ФИЧИНЖИНИРИНГ! Создание новой фичи - средняя цена по категории недвижимости.
# Это помогает модели учитывать "престижность" или типичную стоимость объектов определенной категории

1

In [14]:
#train_data['stage_cat'].value_counts()

In [15]:
train_data

,region_name_cat,district_cat,corpus_cat,developer_cat,agreement_date,floor,square,rooms_4,location_logs_count_mean,location_depth,location_logs_count_std,location_flash_mean_mean,location_hds_ratio_mean_mean,location_hotel_w_mean_distance,location_pop_bank_w_mean_distance,location_natural_cnt,location_office_w_mean_distance,location_depth.1,location_barrier_w_mean_distance,location_amenity_bank_w_mean_distance,location_farmland_cnt,location_car_rental_cnt,location_railway_station_cnt,location_fuel_w_mean_distance,location_commercial_cnt,location_leisure_cnt,location_shop_clothes_w_mean_distance,location_bus_station_cnt,location_mean_levels_mean,location_commercial_w_mean_distance,location_mean_area_density,location_industrial_w_mean_distance,location_town_w_mean_distance,location_residential_w_mean_distance,location_water_cnt,location_pop_cafe_cnt,location_buildings_cnt,location_pop_bank_cnt,location_std_levels_mean,location_amenity_restaurant_w_mean_distance,location_railway_station_w_mean_distance,location_social_w_mean_distance,location_max_levels_max,location_marketplace_cnt,location_public_transport_platform_cnt,location_parking_cnt,location_natural2_cnt,location_highway_traffic_signals_cnt,location_shop_other_w_mean_distance,location_school_w_mean_distance,location_marketplace_w_mean_distance,location_amenity_leisure_w_mean_distance,location_tourism_w_mean_distance,location_shop_alco_cnt,location_motel_cnt,location_market_cnt,location_residential_cnt,location_shop_product_w_mean_distance,location_village_cnt,location_railway_w_mean_distance,location_highway_crossing_w_mean_distance,location_public_transport_stop_position_cnt,location_railway_cnt,location_fuel_cnt,location_industrial_cnt,location_shop_alco_w_mean_distance,location_pop_shop_w_mean_distance,location_suburb_cnt,location_bridge_cnt,location_depth.2,location_college_cnt,location_amenity_pharmacy_w_mean_distance,location_public_transport_stop_position_w_mean_distance,location_public_transport_platform_w_mean_distance,location_water_w_mean_distance,location_university_w_mean_distance,location_leisure_w_mean_distance,location_pop_shop_cnt,square_price_target,hc_name_cat,interior_cat,class_cat,stage_cat,price_target,hc_cat_mean_price
0,Город,58,1331,91,2012-04-13,10.0,78.44,3,23.131066,13.0,21.897417,0.228078,1.323223,0.536679,0.868272,0.0,1.018998,13.0,0.901410,0.776100,0.0,0.0,1.0,0.557765,0.0,182.0,0.824979,0.0,4.433547,-999.000000,0.002067,0.731240,-999.000000,1.131154,9.0,0.0,369.0,3.0,5.678153,1.020871,1.099015,1.145535,25.0,5.0,68.0,137.0,0.0,16.0,0.934210,1.049137,1.000286,-999.000000,0.974185,10.0,0.0,0.0,5.0,0.959757,0.0,1.065862,0.895063,27.0,25.0,3.0,3.0,0.804069,1.032209,0.0,0.0,13.0,1.0,0.983309,1.089198,0.894947,0.772872,1.309514,0.853183,7.0,4.398362,36,0.0,97865,27728,345.007509,262.502915
1,Город,75,1677,91,2013-09-16,2.0,34.15,1,14.090185,13.0,7.942393,0.181002,0.835207,-999.000000,-999.000000,0.0,-999.000000,13.0,0.884374,1.054458,15.0,0.0,0.0,1.226099,0.0,4.0,-999.000000,0.0,0.000000,-999.000000,0.000000,0.604621,-999.000000,0.885340,1.0,0.0,0.0,0.0,0.000000,1.083806,-999.000000,1.263036,0.0,1.0,4.0,8.0,0.0,2.0,1.029732,-999.000000,0.976419,-999.000000,-999.000000,0.0,0.0,0.0,38.0,1.014588,3.0,-999.000000,1.089199,0.0,0.0,1.0,2.0,-999.000000,-999.000000,0.0,0.0,13.0,0.0,1.129674,-999.000000,1.063211,0.840130,-999.000000,1.147596,0.0,4.266639,372,32413.0,97865,70661,145.705705,184.535124
2,Пригород,48,316,10,2014-07-31,17.0,59.85,2,19.453795,13.0,18.504664,0.226871,1.291865,-999.000000,-999.000000,0.0,0.689823,13.0,0.805620,0.887347,2.0,0.0,2.0,-999.000000,0.0,8.0,0.711533,1.0,1.847656,-999.000000,0.002376,1.058737,-999.000000,0.916625,0.0,0.0,62.0,0.0,5.486045,0.779977,0.905319,-999.000000,25.0,5.0,34.0,10.0,0.0,12.0,0.740338,-999.000000,0.600185,0.831753,-999.000000,0.0,0.0,2.0,4.0,0.841496,5.0,0.868288,0.948941,19.0,35.0,0.0,2.0,-999.000000,0.457500,0.0,0.0,13.0,0.0,0.823279,0.806682,0.832622,-999.000000,-999.000000,0.905435,1.0,4.241572,336,8977.0,97865,12638,253.858068,194.351237
3,Пригород,48,1409,91,2012-12-30,12.0,67.53,2,13.178136,13.0,6.480796,0.098885,0.897866,-999.000000,-999.000000,0.0,-999.000000,13.0,1.167388,-999.000000,0.0,0.0,0.0,-999.000000,0.0,1.0,-999.000000,0.0,0.000000,-999.000000,0.000000,-999.000000,-999.000000,1.098454,1.0,0.0,0.0,0.0,-999.000000,-999.000000,-999.000000,-999.000000,0.0,0.0,0.0,0.0,0.0,0.0,-999.000000,-999.000000,-999.000000,-999.000000,1.204801,0.0,0.0,0.0,13.0,-999.000000,0.0,-999.000000,-999.000000,0.0,0.0,0.0,0.0,-999.000000,-999.000000,0.0,0.0,13.0,0.0,-999.000000,-999.000000,-999.000000,1.322121,-999.000000,1.263878,0.0,4.230938,154,32413.0,97865,70661,285.715216,177.975004
4,Пригород,48,1590,91,2014-06-20,5.0,58.13,2,20.691770,13.0,17.940453,0.143889,1.246060,-999.000000,-999.000000,0.0,1.488944,13.0,0.979091,-999.000000,1.0,0.0,1.0,-999.000000,1.0,23.0,-999.000000,0.0,2.548769,1.488944,0.001667,-999.000000,-999.000000,1.001892,1.0,0.0,233.0,0.0,3.223514,-999.000000,1.023568,1.430199,16.0,1.0,20.0,43.0,0.0,8.0,0.928117,0.884511,0.979399,-999.000000,-999.000000,0.0,0.0,0.0,4.0,0.905822,7.0,1.038136,0.879862,3.0,6.0,0.0,0.0,-999.000000,0.909767,0.0,0.0,13.0,0.0,0.783028,0.896906,0.825295,0.996629,-999.000000,1.024595,2.0,4.233818,154,32413.0,97865,12638,246.111845,177.975004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93450,Город,49,811,66,2014-02-28,7.0,44.89,1,22.735272,13.0,21.580344,0.214648,1.318406,0.848237,0.678586,0.0,0.720925,13.0,0.838332,0.750853,0.0,0.0,1.0,0.770194,2.0,52.0,0.725437,0.0,3.394868,1.294953,0.002362,0.785894,-999.000000,0.597527,0.0,1.0,213.0,4.0,5.812795,0.487014,0.753650,0.762774,32.0,7.0,30.0,45.0,0.0,25.0,0.775467,0.498517,0.883101,-999.000000,1.086470,3.0,0.0,0.0,5.0,0.821497,0.0,0.714632,0.726906,36.0,126.0,4.0,7.0,0.415047,0.679361,1.0,0.0,13.0,2.0,0.696053,0.798982,0.902007,-999.000000,0.795061,0.788854,5.0,4.456358,399,49786.0,97865,7983,200.045918,265.200221
93451,Город,34,183,67,2012-06-01,4.0,29.63,1,23.963891,13.0,22.930959,0.223445,1.315551,1.035031,0.816017,1.0,0.986491,13.0,0.948114,0.947254,0.0,0.0,4.0,0.598755,4.0,143.0,1.002101,0.0,4.154709,0.977318,0.003322,0.837179,0.035000,0.999554,0.0,5.0,541.0,6.0,4.867966,0.864020,1.026142,1.053130,26.0,3.0,54.0,62.0,0.0,39.0,1.024493,1.042508,0.837146,1.003652,0.911305,8.0,0.0,2.0,19.0,1.054283,0.0,1.029375,0.990091,48.0,250.0,3.0,6.0,1.058920,1.152083,2.0,0.0,13.0,1.0,1.041811,1.001153,0.963241,-999.000000,1.007377,0.997757,9.0,4.372401,381,0.0,27353,3321,129.554230,315.325205
93452,Город,75,1691,91,2013-07-20,10.0,30.00,1,21.324701,13.0,19.296541,0.182668,1.148408,-999.000000,0.966929,1.0,1.225918,13.0,0.914801,1.192645,0.0,0.0,1.0,1.001718,0.0,119.0,1.428383,0.0,5.045635,-999.000000,0.001697,-999.000000,0.419007,0.881525,2.0,3.0,176.0,3.0,7.399511,1.197463,1.356309,1.066483,39.0,3.0,40.0,82.0,0.0,22.0,1.132978,0.964638,1.230561,0.714214,1.085103,1.0,0.0,0.0,5.0,1.002854,0.0,1.196169,0.927086,18.0,32.0,3.0,0.0,1.314825,0.956165,1.0,0.0,13.0,0.0,1.222633,1.051451,0.978269,0.753894,-999.000000,0.840905,12.0,4.234177,372,49786.0,97865,12638,127.025304,184.535124
93453,Город,1,2198,134,2014-01-09,22.0,108.63,3,24.286312,13.0,24.752685,0.227589,1.322269,0.670050,1.152944,0.0,0.881701,13.0,0.964123,0.931763,0.0,0.0,2.0,0.927740,3.0,162.0,0.908218,0.0,4.571485,0.676991,0.002474,-999.000000,-999.000000,0.683230,2.0,1.0,600.0,4.0,4.699059,0.799676,0.883818,0.942935,26.0,11.0,77.0,75.0,1.0,63.0,0.862520,0.802284,0.885045,0.887363,0.922486,6.0,0.0,0.0,16.0,0.873817,0.0,1.134951,0.926197,82.0,59.0,4.0,0.0,0.942893,0.726233,1.0,1.0,13.0,0.0,0.858863,0.902165,0.886209,1.161560,0.736073,0.920557,11.0,4.653420,213,49786.0,27353,70661,505.500994,367.589611
93454,Город,41,2250,97,2012-05-27,18.0,57.34,2,22.265628,13.0,21.503731,0.293369,1.302297,0.876953,0.787913,0.0,1.171911,13.0,0.929104,0.901190,0.0,0.0,1.0,1.007737,1.0,128.0,0.934170,0.0,4.504036,1.086861,0.002244,0.934854,-999.000000,0.653299,5.0,0.0,395.0,2.0,6.056300,0.424865,0.573470,0.799156,35.0,15.0,61.0,56.0,4.0,8.0,0.913645,0.905502,0.895168,0.591310,0.556700,12.0,0.0,1.0,3.0,0.908051,0.0,0.855410,0.912798,4.0,25.0,2.0,5.0,0.772096,0.857730,1.0,0.0,13.0,1.0,0.947190,0.868109,0.921279,1.392381,-999.000000,0.857490,10.0,4.257883,202,0.0,97865,27728,244.146999,196.938461

In [16]:

test_data = test_data.merge(
    price_mean_hc,
    on = "hc_name_cat",
    how="left",
    suffixes=('_left', '_right')
)

test_data.rename(columns={'price_target': 'hc_cat_mean_price'}, inplace=True)

# Комментарий: Применяем то же преобразование к тестовым данным - добавляем среднюю цену по категориям

In [17]:
price_mean_st = train_data.groupby("stage_cat")['price_target'].mean().reset_index()

print("1")

train_data = train_data.merge(
    price_mean_st,
    on = "stage_cat",
    how="left",
    suffixes=('_left', '_right')
)
#train_data.head(30)
train_data.rename(columns={"price_target_left": 'price_target', 'price_target_right': 'st_cat_mean_price'}, inplace=True)

# Комментарий: ФИЧИНЖИНИРИНГ! Создание новой фичи - средняя цена по категории недвижимости.
# Это помогает модели учитывать "престижность" или типичную стоимость объектов определенной категории

1

In [18]:
test_data.head()

,region_name_cat,district_cat,corpus_cat,developer_cat,agreement_date,floor,square,rooms_4,location_logs_count_mean,location_depth,location_logs_count_std,location_flash_mean_mean,location_hds_ratio_mean_mean,location_hotel_w_mean_distance,location_pop_bank_w_mean_distance,location_natural_cnt,location_office_w_mean_distance,location_depth.1,location_barrier_w_mean_distance,location_amenity_bank_w_mean_distance,location_farmland_cnt,location_car_rental_cnt,location_railway_station_cnt,location_fuel_w_mean_distance,location_commercial_cnt,location_leisure_cnt,location_shop_clothes_w_mean_distance,location_bus_station_cnt,location_mean_levels_mean,location_commercial_w_mean_distance,location_mean_area_density,location_industrial_w_mean_distance,location_town_w_mean_distance,location_residential_w_mean_distance,location_water_cnt,location_pop_cafe_cnt,location_buildings_cnt,location_pop_bank_cnt,location_std_levels_mean,location_amenity_restaurant_w_mean_distance,location_railway_station_w_mean_distance,location_social_w_mean_distance,location_max_levels_max,location_marketplace_cnt,location_public_transport_platform_cnt,location_parking_cnt,location_natural2_cnt,location_highway_traffic_signals_cnt,location_shop_other_w_mean_distance,location_school_w_mean_distance,location_marketplace_w_mean_distance,location_amenity_leisure_w_mean_distance,location_tourism_w_mean_distance,location_shop_alco_cnt,location_motel_cnt,location_market_cnt,location_residential_cnt,location_shop_product_w_mean_distance,location_village_cnt,location_railway_w_mean_distance,location_highway_crossing_w_mean_distance,location_public_transport_stop_position_cnt,location_railway_cnt,location_fuel_cnt,location_industrial_cnt,location_shop_alco_w_mean_distance,location_pop_shop_w_mean_distance,location_suburb_cnt,location_bridge_cnt,location_depth.2,location_college_cnt,location_amenity_pharmacy_w_mean_distance,location_public_transport_stop_position_w_mean_distance,location_public_transport_platform_w_mean_distance,location_water_w_mean_distance,location_university_w_mean_distance,location_leisure_w_mean_distance,location_pop_shop_cnt,hc_name_cat,interior_cat,class_cat,stage_cat,hc_cat_mean_price
0,Пригород,48,1894,91,2014-11-30,18.0,47.58,2,19.446927,13.0,18.097539,0.227314,1.273709,-999.000000,-999.000000,0.0,0.771040,13.0,0.770815,0.420843,2.0,0.0,1.0,-999.000000,0.0,10.0,0.404580,1.0,3.244186,-999.000000,0.002372,1.221898,-999.000000,0.834901,0.0,0.0,59.0,0.0,7.384294,0.463147,0.258752,-999.000000,25.0,5.0,30.0,12.0,0.0,11.0,0.606612,1.389532,0.753266,0.664812,-999.000000,0.0,0.0,2.0,3.0,0.570254,4.0,0.471240,0.792035,15.0,29.0,0.0,2.0,-999.000000,0.086251,0.0,0.0,13.0,0.0,0.813745,0.535582,0.628607,-999.000000,-999.0,0.849043,1.0,368,32413.0,97865,27728,194.669428
1,Город,41,1789,97,2014-09-26,16.0,55.47,2,22.280879,13.0,21.438566,0.297468,1.299495,0.768994,0.818618,0.0,1.037436,13.0,0.933568,0.921481,0.0,0.0,1.0,1.012504,1.0,126.0,1.003154,0.0,4.219991,0.973309,0.002344,0.898938,-999.000000,0.759468,12.0,0.0,400.0,2.0,5.795406,0.414281,0.461189,0.788025,35.0,14.0,60.0,53.0,4.0,4.0,0.902096,0.886345,0.931849,0.601568,0.573186,12.0,0.0,1.0,4.0,0.902201,0.0,0.774316,0.856592,4.0,25.0,2.0,5.0,0.809614,0.901730,1.0,0.0,13.0,1.0,0.941765,0.791124,0.946751,1.414248,-999.0,0.880100,10.0,202,49786.0,97865,27728,196.938461
2,Пригород,48,1164,91,2014-11-12,3.0,39.35,2,19.469961,13.0,15.641484,0.249220,1.185299,-999.000000,-999.000000,0.0,1.088841,13.0,1.108363,1.218117,1.0,0.0,1.0,1.549336,0.0,11.0,1.068556,1.0,2.324818,-999.000000,0.003337,-999.000000,1.373745,1.177891,1.0,0.0,78.0,0.0,5.977160,1.016770,1.242402,-999.000000,25.0,2.0,27.0,8.0,0.0,7.0,1.083711,-999.000000,1.180746,1.074411,-999.000000,0.0,0.0,0.0,7.0,0.985299,3.0,1.376925,1.034488,10.0,56.0,1.0,0.0,-999.000000,1.389367,0.0,0.0,13.0,0.0,1.162024,1.217568,1.077942,1.382267,-999.0,1.122493,1.0,154,32413.0,97865,27728,177.975004
3,Город,78,682,65,2014-08-29,15.0,63.72,2,21.683678,13.0,20.646847,0.169074,1.299957,-999.000000,1.235375,0.0,0.940488,13.0,0.852898,1.115288,0.0,0.0,2.0,1.115353,0.0,140.0,1.209237,0.0,4.325738,-999.000000,0.002792,0.938094,0.879039,1.145172,3.0,0.0,334.0,2.0,6.307885,0.391414,0.845249,1.085257,23.0,5.0,55.0,80.0,1.0,17.0,0.772986,0.915897,1.144783,0.854952,-999.000000,7.0,0.0,1.0,6.0,0.860320,0.0,0.713166,0.855481,25.0,106.0,5.0,5.0,0.400067,0.748802,1.0,0.0,13.0,0.0,0.839195,0.879767,0.857233,0.898411,-999.0,0.786385,6.0,267,12415.0,97865,70661,228.915568
4,Пригород,48,1651,20,2014-11-21,19.0,51.58,2,20.074178,13.0,19.515872,0.177730,1.295727,-999.000000,1.273566,0.0,1.211518,13.0,0.831294,1.070651,0.0,0.0,1.0,0.881055,0.0,23.0,-999.000000,0.0,2.557724,-999.000000,0.002990,0.514612,1.267209,0.896736,0.0,1.0,238.0,2.0,3.776768,1.105369,1.053436,-999.000000,17.0,3.0,22.0,10.0,0.0,3.0,1.062416,1.191248,0.897671,-999.000000,0.987727,0.0,0.0,0.0,4.0,1.111616,1.0,1.073609,1.043449,6.0,8.0,8.0,1.0,-999.000000,1.319090,0.0,0.0,13.0,0.0,1.170772,1.121173,1.053681,-999.000000,-999.0,1.125673,1.0,362,49786.0,97865,70661,173.574080

In [19]:

test_data = test_data.merge(
    price_mean_st,
    on = "stage_cat",
    how="left",
    suffixes=('_left', '_right')
)

test_data.rename(columns={'price_target': 'st_cat_mean_price'}, inplace=True)

# Комментарий: Применяем то же преобразование к тестовым данным - добавляем среднюю цену по категориям

In [20]:
price_mean_reg = train_data.groupby("region_name_cat")['price_target'].mean().reset_index()

print("1")

train_data = train_data.merge(
    price_mean_reg,
    on = "region_name_cat",
    how="left",
    suffixes=('_left', '_right')
)
#train_data.head(30)
train_data.rename(columns={"price_target_left": 'price_target', 'price_target_right': 'region_cat_mean_price'}, inplace=True)

# Комментарий: ФИЧИНЖИНИРИНГ! Создание новой фичи - средняя цена по категории недвижимости.
# Это помогает модели учитывать "престижность" или типичную стоимость объектов определенной категории

1

In [21]:

test_data = test_data.merge(
    price_mean_reg,
    on = "region_name_cat",
    how="left",
    suffixes=('_left', '_right')
)

test_data.rename(columns={'price_target': 'region_cat_mean_price'}, inplace=True)

# Комментарий: Применяем то же преобразование к тестовым данным - добавляем среднюю цену по категориям

In [22]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

def prepare_data(df, name ):
    print(f"{50 * '-'}\nStart preprocessing {name}\n{50 * '-'}")
    df['agreement_date'] = pd.to_datetime(df['agreement_date'])
    
    df['year'] = df['agreement_date'].dt.year
    df['month'] = df['agreement_date'].dt.month
    df['is_lux'] = (df['stage_cat_70661'].astype(int) | df['stage_cat_27728'].astype(int))
    df['is_sred'] = (df['stage_cat_12638'].astype(int) | df['stage_cat_7983'].astype(int))
    df['is_nishebrodina'] = (df['stage_cat_2665'].astype(int) | df['stage_cat_2700'].astype(int) | df['stage_cat_3321'].astype(int))

   # df = df.drop('agreement_date', axis = 1)
    #print(train_data.head())
    # df['house_age'] = abs(2012 - df['year'])
    # df['week'] = df['agreement_date'].dt.isocalendar().week
    df['weekday'] = df['agreement_date'].dt.weekday
    # df['season'] = df['agreement_date'].dt.month % 12 // 3
    # for cl in df.columns:
    #     if df[cl].isna().sum() > 0:
    #         print(f"Nan's in {cl} : {df[cl].isna().sum()}")
    for cl in df.columns:
        if (df[cl].isna().sum() > 0):
            if (df[cl].dtype in ['object', 'category']):
                df[cl] = df[cl].fillna(df[cl].mode[0])
            else :
                df[cl] = df[cl].fillna(df[cl].median())
    
    for cl in df.columns:
        if list(df[cl]).count(-999.000000)  > 0:
            df[cl] = df[cl].replace(-999.000000, df[cl].median())
            print(f"count -999's in {cl} : {list(df[cl]).count(-999.000000)}")
            if (list(df[cl]).count(-999.000000)  >= 65028):
                print(f"Drop {cl} : {list(df[cl]).count(-999.000000)}")

    for cl in df.columns:
        if df[cl].isna().sum() > 0:
            print(f"Nan's in {cl} : {df[cl].isna().sum()}")
    print(f"End of preprocessing {name}")
    return df
ohe_cols = ['rooms_4', 'region_name_cat', 'developer_cat', 'class_cat', 'stage_cat']
# for cl in set(train_data.columns) & set(test_data.columns):
#     if train_data[cl].dtype == "category":
#     #if len(train_data[cl].unique()) < 11 or len(test_data[cl].unique()) < 11:
#         print(f"OneHot in {cl} : {train_data[cl].unique()}")
#         ohe_cols.append(cl)

ohe = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='ignore')

train_ohe = ohe.fit_transform(train_data[ohe_cols])
test_ohe = ohe.transform(test_data[ohe_cols])

train_ohe_df = pd.DataFrame(train_ohe, columns=ohe.get_feature_names_out(ohe_cols), index=train_data.index)
test_ohe_df = pd.DataFrame(test_ohe, columns=ohe.get_feature_names_out(ohe_cols), index=test_data.index)


train_data = pd.concat([train_data.drop(columns=ohe_cols), train_ohe_df], axis=1)
test_data = pd.concat([test_data.drop(columns=ohe_cols), test_ohe_df], axis=1)


# Initialize and fit LabelEncoder
# le = LabelEncoder()
# train_data['region_name_cat'] = le.fit_transform(train_data['region_name_cat'])

# test_data['region_name_cat'] = le.transform(test_data['region_name_cat'])

# le = LabelEncoder()
# train_data['developer_cat'] = le.fit_transform(train_data['developer_cat'])

# test_data['developer_cat'] = le.transform(test_data['developer_cat'])


# le = LabelEncoder()
# train_data['class_cat'] = le.fit_transform(train_data['class_cat'])

# test_data['class_cat'] = le.transform(test_data['class_cat'])


# le = LabelEncoder()

# train_data['stage_cat'] = le.fit_transform(train_data['stage_cat'])
# test_data['stage_cat'] = le.transform(test_data['stage_cat'])
for cl in (set(train_data.columns) & set(test_data.columns)):
        if len(train_data[cl].unique()) == 1 or len(test_data[cl].unique()) == 1:
            print(f"Columns {cl}, has : {len(train_data[cl].unique())}")
            train_data = train_data.drop(cl, axis = 1)
            test_data = test_data.drop(cl, axis = 1)

train_data = prepare_data(train_data, "train_data")
test_data = prepare_data(test_data, "test_data")

# print(train_data.head())
# print(test_data.head())

# Комментарий: ПРЕОБРАЗОВАНИЕ ДАННЫХ! 
# 1. Обработка пропусков: для категориальных - мода, для числовых - медиана
# 2. Замена специального значения -999 на медиану (это явно пропуски в данных)
# 3. One-Hot Encoding для категориальных признаков 'rooms_4' и LabelEncoder для 'region_name_cat'
#    Преобразует категории в бинарные столбцы для работы алгоритмов машинного обучения

/opt/jupyter/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:246: UserWarning: Found unknown categories in columns [2] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(

Columns developer_cat_12, has : 2
Columns developer_cat_51, has : 2
Columns developer_cat_85, has : 2
Columns developer_cat_13, has : 2
Columns developer_cat_115, has : 2
Columns developer_cat_29, has : 2
Columns developer_cat_96, has : 2
Columns developer_cat_53, has : 2
Columns developer_cat_107, has : 2
Columns developer_cat_110, has : 2
Columns developer_cat_86, has : 2
Columns developer_cat_34, has : 2
Columns developer_cat_75, has : 2
Columns developer_cat_45, has : 2
Columns developer_cat_98, has : 2
Columns developer_cat_46, has : 2
Columns developer_cat_25, has : 2
Columns developer_cat_125, has : 2
Columns developer_cat_81, has : 2
Columns developer_cat_61, has : 2
Columns developer_cat_70, has : 2
Columns developer_cat_112, has : 2
Columns developer_cat_15, has : 2
--------------------------------------------------
Start preprocessing train_data
--------------------------------------------------
count -999's in location_hotel_w_mean_distance : 0
count -999's in location_pop_bank_w_mean_distance : 0
count -999's in location_office_w_mean_distance : 0
count -999's in location_amenity_bank_w_mean_distance : 0
count -999's in location_fuel_w_mean_distance : 0
count -999's in location_shop_clothes_w_mean_distance : 0
count -999's in location_commercial_w_mean_distance : 65028
Drop location_commercial_w_mean_distance : 65028
count -999's in location_industrial_w_mean_distance : 0
count -999's in location_town_w_mean_distance : 70828
Drop location_town_w_mean_distance : 70828
count -999's in location_residential_w_mean_distance : 0
count -999's in location_std_levels_mean : 0
count -999's in location_amenity_restaurant_w_mean_distance : 0
count -999's in location_railway_station_w_mean_distance : 0
count -999's in location_social_w_mean_distance : 0
count -999's in location_shop_other_w_mean_distance : 0
count -999's in location_school_w_mean_distance : 0
count -999's in location_marketplace_w_mean_distance : 0
count -999's in location_amenity_leisure_w_mean_distance : 0
count -999's in location_tourism_w_mean_distance : 0
count -999's in location_shop_product_w_mean_distance : 0
count -999's in location_railway_w_mean_distance : 0
count -999's in location_highway_crossing_w_mean_distance : 0
count -999's in location_shop_alco_w_mean_distance : 0
count -999's in location_pop_shop_w_mean_distance : 0
count -999's in location_amenity_pharmacy_w_mean_distance : 0
count -999's in location_public_transport_stop_position_w_mean_distance : 0
count -999's in location_public_transport_platform_w_mean_distance : 0
count -999's in location_water_w_mean_distance : 0
count -999's in location_university_w_mean_distance : 68831
Drop location_university_w_mean_distance : 68831
End of preprocessing train_data
--------------------------------------------------
Start preprocessing test_data
--------------------------------------------------
count -999's in location_hotel_w_mean_distance : 0
count -999's in location_pop_bank_w_mean_distance : 0
count -999's in location_office_w_mean_distance : 0
count -999's in location_amenity_bank_w_mean_distance : 0
count -999's in location_fuel_w_mean_distance : 0
count -999's in location_shop_clothes_w_mean_distance : 0
count -999's in location_commercial_w_mean_distance : 20398
count -999's in location_industrial_w_mean_distance : 0
count -999's in location_town_w_mean_distance : 24178
count -999's in location_residential_w_mean_distance : 0
count -999's in location_amenity_restaurant_w_mean_distance : 0
count -999's in location_railway_station_w_mean_distance : 0
count -999's in location_social_w_mean_distance : 0
count -999's in location_shop_other_w_mean_distance : 0
count -999's in location_school_w_mean_distance : 0
count -999's in location_marketplace_w_mean_distance : 0
count -999's in location_amenity_leisure_w_mean_distance : 0
count -999's in location_tourism_w_mean_distance : 0
count -999's in location_shop_product_w_mean_distance : 0
count -999's in location_railway_w_mean_distance : 0
count -999's in location_highway_crossing_w_mean_distance : 0
count -999's in location_shop_alco_w_mean_distance : 0
count -999's in location_pop_shop_w_mean_distance : 0
count -999's in location_amenity_pharmacy_w_mean_distance : 0
count -999's in location_public_transport_stop_position_w_mean_distance : 0
count -999's in location_public_transport_platform_w_mean_distance : 0
count -999's in location_water_w_mean_distance : 0
count -999's in location_university_w_mean_distance : 22094
End of preprocessing test_data

In [23]:
# test_data

In [24]:
import hdbscan
import numpy as np
cols = [c for c in train_data.columns if c.startswith("location_")]
#cols.append('corpus_cat')
# Initialize and fit HDBSCAN
clusterer = hdbscan.HDBSCAN(min_cluster_size=20, min_samples=7, prediction_data=True)
train_data['cluster'] = clusterer.fit_predict(train_data[cols])

# Get cluster sizes (correct way)
cluster_sizes = train_data['cluster'].value_counts()
train_data['cluster_size'] = train_data['cluster'].map(cluster_sizes)

# Calculate mean transaction sum per cluster, handling noise

/opt/jupyter/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(
/opt/jupyter/lib/python3.12/site-packages/sklearn/utils/deprecation.py:132: FutureWarning: 'force_all_finite' was renamed to 'ensure_all_finite' in 1.6 and will be removed in 1.8.
  warnings.warn(

In [25]:
train_data

,district_cat,corpus_cat,agreement_date,floor,square,location_logs_count_mean,location_depth,location_logs_count_std,location_flash_mean_mean,location_hds_ratio_mean_mean,location_hotel_w_mean_distance,location_pop_bank_w_mean_distance,location_natural_cnt,location_office_w_mean_distance,location_depth.1,location_barrier_w_mean_distance,location_amenity_bank_w_mean_distance,location_farmland_cnt,location_car_rental_cnt,location_railway_station_cnt,location_fuel_w_mean_distance,location_commercial_cnt,location_leisure_cnt,location_shop_clothes_w_mean_distance,location_bus_station_cnt,location_mean_levels_mean,location_commercial_w_mean_distance,location_mean_area_density,location_industrial_w_mean_distance,location_town_w_mean_distance,location_residential_w_mean_distance,location_water_cnt,location_pop_cafe_cnt,location_buildings_cnt,location_pop_bank_cnt,location_std_levels_mean,location_amenity_restaurant_w_mean_distance,location_railway_station_w_mean_distance,location_social_w_mean_distance,location_max_levels_max,location_marketplace_cnt,location_public_transport_platform_cnt,location_parking_cnt,location_natural2_cnt,location_highway_traffic_signals_cnt,location_shop_other_w_mean_distance,location_school_w_mean_distance,location_marketplace_w_mean_distance,location_amenity_leisure_w_mean_distance,location_tourism_w_mean_distance,location_shop_alco_cnt,location_motel_cnt,location_market_cnt,location_residential_cnt,location_shop_product_w_mean_distance,location_village_cnt,location_railway_w_mean_distance,location_highway_crossing_w_mean_distance,location_public_transport_stop_position_cnt,location_railway_cnt,location_fuel_cnt,location_industrial_cnt,location_shop_alco_w_mean_distance,location_pop_shop_w_mean_distance,location_suburb_cnt,location_bridge_cnt,location_depth.2,location_college_cnt,location_amenity_pharmacy_w_mean_distance,location_public_transport_stop_position_w_mean_distance,location_public_transport_platform_w_mean_distance,location_water_w_mean_distance,location_university_w_mean_distance,location_leisure_w_mean_distance,location_pop_shop_cnt,square_price_target,hc_name_cat,interior_cat,price_target,hc_cat_mean_price,st_cat_mean_price,region_cat_mean_price,rooms_4_2,rooms_4_3,rooms_4_>=4,rooms_4_студия,region_name_cat_Область,region_name_cat_Пригород,developer_cat_2,developer_cat_4,developer_cat_7,developer_cat_8,developer_cat_9,developer_cat_10,developer_cat_14,developer_cat_16,developer_cat_17,developer_cat_18,developer_cat_20,developer_cat_21,developer_cat_22,developer_cat_23,developer_cat_27,developer_cat_30,developer_cat_32,developer_cat_33,developer_cat_38,developer_cat_39,developer_cat_41,developer_cat_42,developer_cat_43,developer_cat_44,developer_cat_47,developer_cat_49,developer_cat_52,developer_cat_57,developer_cat_58,developer_cat_60,developer_cat_62,developer_cat_63,developer_cat_65,developer_cat_66,developer_cat_67,developer_cat_68,developer_cat_69,developer_cat_72,developer_cat_73,developer_cat_74,developer_cat_76,developer_cat_77,developer_cat_78,developer_cat_79,developer_cat_80,developer_cat_82,developer_cat_88,developer_cat_91,developer_cat_92,developer_cat_97,developer_cat_99,developer_cat_100,developer_cat_101,developer_cat_104,developer_cat_105,developer_cat_111,developer_cat_116,developer_cat_118,developer_cat_120,developer_cat_121,developer_cat_124,developer_cat_126,developer_cat_127,developer_cat_128,developer_cat_129,developer_cat_130,developer_cat_132,developer_cat_134,developer_cat_137,class_cat_27353,class_cat_97865,stage_cat_2665,stage_cat_2700,stage_cat_3321,stage_cat_7983,stage_cat_12638,stage_cat_27728,stage_cat_70661,year,month,is_lux,is_sred,is_nishebrodina,weekday,cluster,cluster_size
0,58,1331,2012-04-13,10.0,78.44,23.131066,13.0,21.897417,0.228078,1.323223,0.536679,0.868272,0.0,1.018998,13.0,0.901410,0.776100,0.0,0.0,1.0,0.557765,0.0,182.0,0.824979,0.0,4.433547,-999.000000,0.002067,0.731240,-999.000000,1.131154,9.0,0.0,369.0,3.0,5.678153,1.020871,1.099015,1.145535,25.0,5.0,68.0,137.0,0.0,16.0,0.934210,1.049137,1.000286,0.688975,0.974185,10.0,0.0,0.0,5.0,0.959757,0.0,1.065862,0.895063,27.0,25.0,3.0,3.0,0.804069,1.032209,0.0,0.0,13.0,1.0,0.983309,1.089198,0.894947,0.772872,1.309514,0.853183,7.0,4.398362,36,0.0,345.007509,262.502915,254.607824,268.425104,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2012,4,1,0,0,4,98,620
1,75,1677,2013-09-16,2.0,34.15,14.090185,13.0,7.942393,0.181002,0.835207,0.768994,0.868272,0.0,0.863632,13.0,0.884374,1.054458,15.0,0.0,0.0,1.226099,0.0,4.0,0.945402,0.0,0.000000,-999.000000,0.000000,0.604621,-999.000000,0.885340,1.0,0.0,0.0,0.0,0.000000,1.083806,0.714739,1.263036,0.0,1.0,4.0,8.0,0.0,2.0,1.029732,0.908094,0.976419,0.688975,0.911305,0.0,0.0,0.0,38.0,1.014588,3.0,0.842107,1.089199,0.0,0.0,1.0,2.0,0.772461,0.891318,0.0,0.0,13.0,0.0,1.129674,0.852734,1.063211,0.840130,-999.000000,1.147596,0.0,4.266639,372,32413.0,145.705705,184.535124,248.024882,268.425104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2013,9,1,0,0,0,187,334
2,48,316,2014-07-31,17.0,59.85,19.453795,13.0,18.504664,0.226871,1.291865,0.768994,0.868272,0.0,0.689823,13.0,0.805620,0.887347,2.0,0.0,2.0,0.849300,0.0,8.0,0.711533,1.0,1.847656,-999.000000,0.002376,1.058737,-999.000000,0.916625,0.0,0.0,62.0,0.0,5.486045,0.779977,0.905319,0.811307,25.0,5.0,34.0,10.0,0.0,12.0,0.740338,0.908094,0.600185,0.831753,0.911305,0.0,0.0,2.0,4.0,0.841496,5.0,0.868288,0.948941,19.0,35.0,0.0,2.0,0.772461,0.457500,0.0,0.0,13.0,0.0,0.823279,0.806682,0.832622,0.813515,-999.000000,0.905435,1.0,4.241572,336,8977.0,253.858068,194.351237,219.917162,188.616487,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2014,7,0,1,0,3,233,565
3,48,1409,2012-12-30,12.0,67.53,13.178136,13.0,6.480796,0.098885,0.897866,0.768994,0.868272,0.0,0.863632,13.0,1.167388,0.919339,0.0,0.0,0.0,0.849300,0.0,1.0,0.945402,0.0,0.000000,-999.000000,0.000000,0.840130,-999.000000,1.098454,1.0,0.0,0.0,0.0,6.038867,0.864020,0.714739,0.811307,0.0,0.0,0.0,0.0,0.0,0.0,0.885841,0.908094,0.903011,0.688975,1.204801,0.0,0.0,0.0,13.0,0.865972,0.0,0.842107,0.879862,0.0,0.0,0.0,0.0,0.772461,0.891318,0.0,0.0,13.0,0.0,0.882552,0.852734,0.881220,1.322121,-999.000000,1.263878,0.0,4.230938,154,32413.0,285.715216,177.975004,248.024882,188.616487,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2012,12,1,0,0,6,199,250
4,48,1590,2014-06-20,5.0,58.13,20.691770,13.0,17.940453,0.143889,1.246060,0.768994,0.868272,0.0,1.488944,13.0,0.979091,0.919339,1.0,0.0,1.0,0.849300,1.0,23.0,0.945402,0.0,2.548769,1.488944,0.001667,0.840130,-999.000000,1.001892,1.0,0.0,233.0,0.0,3.223514,0.864020,1.023568,1.430199,16.0,1.0,20.0,43.0,0.0,8.0,0.928117,0.884511,0.979399,0.688975,0.911305,0.0,0.0,0.0,4.0,0.905822,7.0,1.038136,0.879862,3.0,6.0,0.0,0.0,0.772461,0.909767,0.0,0.0,13.0,0.0,0.783028,0.896906,0.825295,0.996629,-999.000000,1.024595,2.0,4.233818,154,32413.0,246.111845,177.975004,219.917162,188.616487,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2014,6,0,1,0,4,60,142
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93450,49,811,2014-02-28,7.0,44.89,22.735272,13.0,21.580344,0.214648,1.318406,0.848237,0.678586,0.0,0.720925,13.0,0.838332,0.750853,0.0,0.0,1.0,0.770194,2.0,52.0,0.725437,0.0,3.394868,1.294953,0.002362,0.785894,-999.000000,0.597527,0.0,1.0,213.0,4.0,5.812795,0.487014,0.753650,0.762774,32.0,7.0,30.0,45.0,0.0,25.0,0.775467,0.498517,0.883101,0.688975,1.086470,3.0,0.0,0.0,5.0,0.821497,0.0,0.714632,0.726906,36.0,126.0,4.0,7.0,0.415047,0.679361,1.0,0.0,13.0,2.0,0.696053,0.798982,0.902007,0.813515,0.795061,0.788854,5.0,4.456358,399,49786.0,200.045918,265.200221,263.967963,268.425104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2014,2,0,1,0,4,52,40
93451,34,183,2012-06-01,4.0,29.63,23.963891,13.0,22.930959,0.223445,1.315551,1.035031,0.816017,1.0,0.986491,13.0,0.948114,0.947254,0.0,0.0,4.0,0.598755,4.0,143.0,1.002101,0.0,4.154709,0.977318,0.003322,0.837179,0.035000,0.999554,0.0,5.0,541.0,6.0,4.867966,0.864020,1.026142,1.053130,26.0,3.0,54.0,62.0,0.0,39.0,1.024493,1.042508,0.837146,1.003652,0.911305,8.0,0.0,2.0,19.0,1.054283,0.0,1.029375,0.990091,48.0,250.0,3.0,6.0,1.058920,1.152083,2.0,0.0,13.0,1.0,1.041811,1.001153,0.963241,0.813515,1.007377,0.997757,9.0,4.372401,381,0.0,129.554230,315.325205,243.855809,268.425104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2012,6,0,0,1,4,74,1082
93452,75,1691,2013-07-20,10.0,30.00,21.324701,13.0,19.296541,0.182668,1.148408,0.768994,0.966929,1.0,1.225918,13.0,0.914801,1.192645,0.0,0.0,1.0,1.001718,0.0,119.0,1.428383,0.0,5.045635,-999.000000,0.001697,0.840130,0.419007,0.881525,2.0,3.0,176.0,3.0,7.399511,1.197463,1.356309,1.066483,39.0,3.0,40.0,82.0,0.0,22.0,1.132978,0.964638,1.230561,0.714214,1.085103,1.0,0.0,0.0,5.0,1.002854,0.0,1.196169,0.927086,18.0,32.0,3.0,0.0,1.314825,0.956165,1.0,0.0,13.0,0.0,1.222633,1.051451,0.978269,0.753894,-999.000000,0.840905,12.0,4.234177,372,49786.0,127.025304,184.535124,219.917162,268.425104,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2013,7,0,1,0,5,238,290
93453,1,2198,2014-01-09,22.0,108.63,24.286312,13.0,24.752685,0.227589,1.322269,0.670050,1.152944,0.0,0.881701,13.0,0.964123,0.931763,0.0,0.0,2.0,0.927740,3.0,162.0,0.908218,0.0,4.571485,0.676991,0.002474,0.840130,-999.000000,0.683230,2.0,1.0,600.0,4.0,4.699059,0.799676,0.883818,0.942935,26.0,11.0,77.0,75.0,1.0,63.0,0.862520,0.802284,0.885045,0.887363,0.922486,6.0,0.0,0.0,16.0,0.873817,0.0,1.134951,0.926197,82.0,59.0,4.0,0.0,0.942893,0.726233,1.0,1.0,13.0,0.0,0.858863,0.902165,0.886209,1.161560,0.736073,0.920557,11.0,4.653420,213,49786.0,505.500994,367.589611,248.024882,268.425104,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2014,1,1,0,0,3,266,602
93454,41,2250,2012-05-27,18.0,57.34,22.265628,13.0,21.503731,0.293369,1.302297,0.876953,0.787913,0.0,1.171911,13.0,0.929104,0.901190,0.0,0.0,1.0,1.007737,1.0,128.0,0.934170,0.0,4.504036,1.086861,0.002244,0.934854,-999.000000,0.653299,5.0,0.0,395.0,2.0,6.056300,0.424865,0.573470,0.799156,35.0,15.0,61.0,56.0,4.0,8.0,0.913645,0.905502,0.895168,0.591310,0.556700,12.0,0.0,1.0,3.0,0.908051,0.0,0.855410,0.912798,4.0,25.0,2.0,5.0,0.772096,0.857730,1.0,0.0,13.0,1.0,0.947190,0.868109,0.921279,1.392381,-999.000000,0.857490,10.0,4.257883,202,0.0,244.146999,196.938461,254.607824,268.425104,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2012,5,1,0,0,6,90,999

In [26]:
from hdbscan import approximate_predict

test_data['cluster'], strengths = approximate_predict(clusterer, test_data[cols])

# Get cluster sizes (correct way)
cluster_sizes = test_data['cluster'].value_counts()
test_data['cluster_size'] = test_data['cluster'].map(cluster_sizes)

In [27]:
train_df_mean = (
    train_data.groupby('cluster')['price_target']
    .mean()
    .reset_index()
    .rename(columns={'price_target': 'HDBSCAN'})
)


train_df_mean.head(10)

   cluster     HDBSCAN
0       -1  492.365040
1        0  184.369320
2        1  297.469949
3        2  312.634380
4        3  800.191898
5        4  301.350298
6        5  202.850036
7        6  222.305112
8        7  265.673471
9        8  454.284890

In [28]:
train_df_mean = train_df_mean[train_df_mean['cluster'] != -1]

test_df_mean = train_df_mean[train_df_mean['cluster'] != -1]

In [29]:
train_data = (
    train_data.merge(
        train_df_mean,
        on = "cluster",
        how = "left"
    )
)

In [30]:
test_data = ( 
    test_data.merge(
        train_df_mean,
        on = "cluster",
        how = "left"
    )
)

In [31]:
#cat_features = []

# for cl in train_data.columns :
#     if len(train_data[cl].unique()) == 1 or len(test_data[cl].unique()) == 1:
#         print(f"Columns {cl}, has : {len(train_data[cl].unique())}")

#         train_data = train_data.drop(cl, axis = 1)
#         test_data = test_data.drop(cl, axis = 1)
    # elif len(train_data[cl].unique()) <= 7:
    #     print(f"Columns {cl}, has : {len(train_data[cl].unique())}")
    #     cat_features.append(cl)
    #     train_data[cl] = train_data[cl].astype(int)
    #     test_data[cl] = test_data[cl].astype(int)

#cat_features.remove('year')
#cat_features.remove('month')

In [32]:
# train_data['agreement_date'] = pd.to_datetime(train_data['agreement_date'])

# train_data['year'] = train_data['agreement_date'].dt.year
# train_data['month'] = train_data['agreement_date'].dt.month
# #train_data['day'] = train_data['agreement_date'].dt.day
# train_data = train_data.drop('agreement_date', axis = 1)
# #print(train_data.head())

# test_data['agreement_date'] = pd.to_datetime(test_data['agreement_date'])

# test_data['year'] = test_data['agreement_date'].dt.year
# test_data['month'] = test_data['agreement_date'].dt.month
# # test_data['day'] = test_data['agreement_date'].dt.day
# test_data = test_data.drop('agreement_date', axis = 1)
# #print(train_data.head())

# # Комментарий: РАБОТА С ДАТАМИ! Разбиваем дату на год, месяц и день как отдельные признаки.
# # Это помогает модели учитывать сезонность и временные тренды в ценах на недвижимость

In [33]:
# train_data = train_data.drop('cluster_size', axis = 1)
# test_data = test_data.drop('cluster_size', axis = 1)
# print(train_data.head())

In [34]:
train_data = train_data.drop('HDBSCAN', axis = 1)
test_data = test_data.drop('HDBSCAN', axis = 1)

In [35]:
from catboost import CatBoostRegressor, Pool
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X = train_data.drop(columns=['square_price_target', 'price_target'])
y = train_data['square_price_target']
cat_features = ['developer_cat', 'rooms_4', 'region_name_cat', 'stage_cat', 'class_cat']

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(('square_price_target' in X_train.columns) or ('price_target' in X_train.columns))
model = CatBoostRegressor(
    iterations=10000,
    learning_rate=0.03,
    depth=9,  
    eval_metric='MAPE',
    random_seed=42,
    verbose=400
)
model.fit(
    X_train, y_train,
    eval_set=(X_val, y_val),
    #cat_features=cat_features,
    early_stopping_rounds=50
)
y_pred = model.predict(X_val)
acc = mean_absolute_error(y_val, y_pred)
print(f"MAE: {acc:.4f}")

# Комментарий: ОСНОВНОЕ МОДЕЛИРОВАНИЕ!
# Используем CatBoost - мощный алгоритм для табличных данных
# - 7000 итераций: много, но есть early stopping
# - learning_rate=0.025: умеренная скорость обучения
# - depth=9: достаточно глубокая модель для сложных зависимостей
# - MAE метрика: соответствует метрике соревнования (MAPE)
# - 30% данных на валидацию для контроля переобучения

False
0:	learn: 0.0229701	test: 0.0228717	best: 0.0228717 (0)	total: 71.3ms	remaining: 11m 52s
400:	learn: 0.0038604	test: 0.0038991	best: 0.0038991 (400)	total: 9.02s	remaining: 3m 35s
800:	learn: 0.0032495	test: 0.0033342	best: 0.0033342 (800)	total: 17.9s	remaining: 3m 25s
1200:	learn: 0.0029459	test: 0.0030772	best: 0.0030772 (1200)	total: 26.7s	remaining: 3m 15s
1600:	learn: 0.0027517	test: 0.0029305	best: 0.0029305 (1600)	total: 35.3s	remaining: 3m 5s
2000:	learn: 0.0026081	test: 0.0028294	best: 0.0028294 (2000)	total: 44s	remaining: 2m 55s
2400:	learn: 0.0024951	test: 0.0027533	best: 0.0027533 (2400)	total: 52.7s	remaining: 2m 46s
2800:	learn: 0.0023960	test: 0.0026903	best: 0.0026903 (2800)	total: 1m 1s	remaining: 2m 38s
3200:	learn: 0.0023115	test: 0.0026437	best: 0.0026437 (3200)	total: 1m 10s	remaining: 2m 29s
3600:	learn: 0.0022355	test: 0.0026045	best: 0.0026045 (3600)	total: 1m 19s	remaining: 2m 21s
4000:	learn: 0.0021719	test: 0.0025721	best: 0.0025721 (4000)	total: 1m 28s	remaining: 2m 12s
4400:	learn: 0.0021136	test: 0.0025445	best: 0.0025445 (4400)	total: 1m 36s	remaining: 2m 3s
4800:	learn: 0.0020582	test: 0.0025188	best: 0.0025188 (4800)	total: 1m 45s	remaining: 1m 54s
5200:	learn: 0.0020052	test: 0.0024941	best: 0.0024941 (5200)	total: 1m 54s	remaining: 1m 45s
5600:	learn: 0.0019566	test: 0.0024730	best: 0.0024730 (5600)	total: 2m 3s	remaining: 1m 37s
6000:	learn: 0.0019110	test: 0.0024529	best: 0.0024529 (6000)	total: 2m 12s	remaining: 1m 28s
6400:	learn: 0.0018688	test: 0.0024367	best: 0.0024367 (6400)	total: 2m 21s	remaining: 1m 19s
6800:	learn: 0.0018309	test: 0.0024235	best: 0.0024235 (6800)	total: 2m 30s	remaining: 1m 10s
7200:	learn: 0.0017958	test: 0.0024103	best: 0.0024103 (7200)	total: 2m 39s	remaining: 1m 2s
7600:	learn: 0.0017607	test: 0.0023985	best: 0.0023985 (7600)	total: 2m 49s	remaining: 53.4s
8000:	learn: 0.0017272	test: 0.0023875	best: 0.0023875 (8000)	total: 2m 58s	remaining: 44.5s
8400:	learn: 0.0016948	test: 0.0023771	best: 0.0023771 (8400)	total: 3m 7s	remaining: 35.6s
8800:	learn: 0.0016666	test: 0.0023684	best: 0.0023684 (8800)	total: 3m 16s	remaining: 26.7s
9200:	learn: 0.0016379	test: 0.0023594	best: 0.0023594 (9197)	total: 3m 25s	remaining: 17.8s
9600:	learn: 0.0016103	test: 0.0023514	best: 0.0023514 (9600)	total: 3m 34s	remaining: 8.91s
9999:	learn: 0.0015832	test: 0.0023440	best: 0.0023440 (9994)	total: 3m 43s	remaining: 0us

bestTest = 0.00234400182
bestIteration = 9994

Shrink model to first 9995 iterations.
MAE: 0.0103

In [36]:
import pandas as pd

importances = model.get_feature_importance()
feature_names = X_train.columns

fi = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
}).sort_values("importance", ascending=False)

fi.head(len(fi))

                                               feature    importance
77                                   hc_cat_mean_price  2.815209e+01
155                                    class_cat_27353  9.573521e+00
5                             location_logs_count_mean  5.629885e+00
4                                               square  4.381427e+00
2                                       agreement_date  3.716676e+00
79                               region_cat_mean_price  2.801039e+00
75                                         hc_name_cat  2.037923e+00
3                                                floor  1.843540e+00
0                                         district_cat  1.619529e+00
67                                location_college_cnt  1.501331e+00
58         location_public_transport_stop_position_cnt  1.370291e+00
9                         location_hds_ratio_mean_mean  1.310596e+00
76                                        interior_cat  1.290283e+00
1                                           corpus_cat  1.233704e+00
170                                            cluster  1.145824e+00
60                                   location_fuel_cnt  1.087039e+00
163                                    stage_cat_70661  1.046989e+00
56                    location_railway_w_mean_distance  9.596408e-01
156                                    class_cat_97865  9.411653e-01
11                   location_pop_bank_w_mean_distance  9.127997e-01
73                    location_leisure_w_mean_distance  8.894555e-01
63                   location_pop_shop_w_mean_distance  8.388090e-01
32                               location_pop_cafe_cnt  8.370239e-01
78                                   st_cat_mean_price  7.523857e-01
165                                              month  7.364470e-01
49                    location_tourism_w_mean_distance  7.354554e-01
7                              location_logs_count_std  6.809714e-01
71                      location_water_w_mean_distance  6.682112e-01
13                     location_office_w_mean_distance  6.604658e-01
39                             location_max_levels_max  6.155933e-01
53                            location_residential_cnt  5.998617e-01
59                                location_railway_cnt  5.909185e-01
28                 location_industrial_w_mean_distance  5.858825e-01
16               location_amenity_bank_w_mean_distance  5.806249e-01
68           location_amenity_pharmacy_w_mean_distance  5.656966e-01
25                           location_mean_levels_mean  5.585458e-01
171                                       cluster_size  5.477953e-01
72                 location_university_w_mean_distance  5.395870e-01
45                 location_shop_other_w_mean_distance  5.354133e-01
164                                               year  5.214579e-01
10                      location_hotel_w_mean_distance  5.187963e-01
15                    location_barrier_w_mean_distance  5.172872e-01
127                                   developer_cat_77  5.099327e-01
33                              location_buildings_cnt  5.018641e-01
44                location_highway_traffic_signals_cnt  4.965995e-01
40                            location_marketplace_cnt  4.923845e-01
69   location_public_transport_stop_position_w_mean...  4.904077e-01
54               location_shop_product_w_mean_distance  4.825366e-01
57           location_highway_crossing_w_mean_distance  4.181888e-01
70   location_public_transport_platform_w_mean_dist...  4.172504e-01
23               location_shop_clothes_w_mean_distance  4.056333e-01
81                                           rooms_4_3  3.894928e-01
38                     location_social_w_mean_distance  3.852914e-01
50                              location_shop_alco_cnt  3.750838e-01
22                                location_leisure_cnt  3.686004e-01
35                            location_std_levels_mean  3.665465e-01
20                       location_fuel_w_mean_distance  3.637981e-01
74                               location_pop_shop_cnt  3.605096e-01
30                location_residential_w_mean_distance  3.463312e-01
31                                  location_water_cnt  3.438616e-01
64                                 location_suburb_cnt  3.244701e-01
27                          location_mean_area_density  3.203774e-01
41              location_public_transport_platform_cnt  3.031353e-01
34                               location_pop_bank_cnt  2.819816e-01
36         location_amenity_restaurant_w_mean_distance  2.813275e-01
169                                            weekday  2.800607e-01
80                                           rooms_4_2  2.721691e-01
85                            region_name_cat_Пригород  2.557636e-01
46                     location_school_w_mean_distance  2.502398e-01
26                 location_commercial_w_mean_distance  2.383810e-01
62                  location_shop_alco_w_mean_distance  2.262905e-01
47                location_marketplace_w_mean_distance  2.238965e-01
8                             location_flash_mean_mean  2.230337e-01
52                                 location_market_cnt  2.056083e-01
43                               location_natural2_cnt  1.975290e-01
48            location_amenity_leisure_w_mean_distance  1.658695e-01
42                                location_parking_cnt  1.645664e-01
133                                   developer_cat_91  1.575132e-01
168                                    is_nishebrodina  1.327399e-01
61                             location_industrial_cnt  1.299548e-01
29                       location_town_w_mean_distance  1.293225e-01
19                        location_railway_station_cnt  1.149368e-01
167                                            is_sred  7.771421e-02
162                                    stage_cat_27728  6.930962e-02
82                                         rooms_4_>=4  6.232644e-02
37            location_railway_station_w_mean_distance  6.095029e-02
157                                     stage_cat_2665  5.297494e-02
160                                     stage_cat_7983  4.728406e-02
158                                     stage_cat_2700  4.423346e-02
21                             location_commercial_cnt  4.315080e-02
102                                   developer_cat_32  3.909868e-02
119                                   developer_cat_66  3.006180e-02
12                                location_natural_cnt  2.438335e-02
113                                   developer_cat_57  2.404272e-02
87                                     developer_cat_4  2.383651e-02
94                                    developer_cat_17  1.975881e-02
143                                  developer_cat_118  1.759013e-02
107                                   developer_cat_42  1.714489e-02
100                                   developer_cat_27  1.675349e-02
17                               location_farmland_cnt  1.673503e-02
106                                   developer_cat_41  1.548555e-02
83                                      rooms_4_студия  1.546534e-02
130                                   developer_cat_80  1.514148e-02
120                                   developer_cat_67  1.463722e-02
166                                             is_lux  1.370913e-02
55                                location_village_cnt  1.216503e-02
98                                    developer_cat_22  1.177914e-02
65                                 location_bridge_cnt  1.166838e-02
123                                   developer_cat_72  1.114568e-02
121                                   developer_cat_68  1.073118e-02
91                                    developer_cat_10  1.073043e-02
149                                  developer_cat_128  1.067754e-02
51                                  location_motel_cnt  9.371222e-03
92                                    developer_cat_14  8.740245e-03
136                                   developer_cat_99  8.639133e-03
135                                   developer_cat_97  7.894333e-03
101                                   developer_cat_30  7.484262e-03
145                                  developer_cat_121  7.135644e-03
159                                     stage_cat_3321  7.035640e-03
84                             region_name_cat_Область  6.475967e-03
90                                     developer_cat_9  6.097722e-03
153                                  developer_cat_134  5.520131e-03
18                             location_car_rental_cnt  5.334900e-03
138                                  developer_cat_101  5.213572e-03
152                                  developer_cat_132  5.050295e-03
112                                   developer_cat_52  4.330208e-03
109                                   developer_cat_44  3.832354e-03
99                                    developer_cat_23  3.163259e-03
124                                   developer_cat_73  2.738623e-03
126                                   developer_cat_76  2.718707e-03
118                                   developer_cat_65  2.668353e-03
128                                   developer_cat_78  1.966304e-03
150                                  developer_cat_129  1.762810e-03
151                                  developer_cat_130  1.639055e-03
89                                     developer_cat_8  1.591120e-03
139                                  developer_cat_104  1.534645e-03
86                                     developer_cat_2  1.504387e-03
148                                  developer_cat_127  1.360460e-03
114                                   developer_cat_58  1.317313e-03
24                            location_bus_station_cnt  1.267876e-03
95                                    developer_cat_18  1.109369e-03
111                                   developer_cat_49  9.669229e-04
131                                   developer_cat_82  9.642026e-04
103                                   developer_cat_33  8.897948e-04
161                                    stage_cat_12638  8.712743e-04
93                                    developer_cat_16  7.770003e-04
147                                  developer_cat_126  6.975227e-04
97                                    developer_cat_21  6.847222e-04
129                                   developer_cat_79  6.795751e-04
125                                   developer_cat_74  5.418045e-04
117                                   developer_cat_63  5.279400e-04
115                                   developer_cat_60  5.086709e-04
108                                   developer_cat_43  3.842672e-04
132                                   developer_cat_88  2.082004e-04
137                                  developer_cat_100  1.783523e-04
146                                  developer_cat_124  1.706357e-04
105                                   developer_cat_39  1.042207e-04
140                                  developer_cat_105  9.585742e-05
141                                  developer_cat_111  7.534672e-05
104                                   developer_cat_38  1.829908e-05
134                                   developer_cat_92  6.620590e-06
88                                     developer_cat_7  4.933542e-06
144                                  developer_cat_120  2.254512e-06
116                                   developer_cat_62  2.087853e-06
110                                   developer_cat_47  1.547277e-06
154                                  developer_cat_137  9.037809e-07
14                                    location_depth.1  0.000000e+00
6                                       location_depth  0.000000e+00
96                                    developer_cat_20  0.000000e+00
66                                    location_depth.2  0.000000e+00
122                                   developer_cat_69  0.000000e+00
142                                  developer_cat_116  0.000000e+00

In [37]:
model.predict(test_data)

array([4.2651018 , 4.30677906, 4.30168656, ..., 4.25887364, 4.2626208 ,
       4.26998023], shape=(31492,))

In [38]:
y_pred = model.predict(test_data)
original_price = 10 ** (y_pred)
original_price

array([18412.0353581 , 20266.51413582, 20030.25880003, ...,
       18149.87498987, 18307.15236243, 18620.02375452], shape=(31492,))

In [39]:
pd.read_csv("train.csv")['price_target'][:20]

0     25024.299281
1     18477.300271
2     17441.013879
3     17019.139763
4     17132.394908
5     39929.201075
6     71538.911990
7     18080.907198
8     20317.697011
9     37419.773430
10    25626.533774
11    16304.357946
12    28385.713345
13    27923.632109
14    20813.188377
15    17656.200224
16    19884.494573
17    16537.805234
18    26546.732049
19    34712.429609
Name: price_target, dtype: float64

In [40]:
subm = pd.DataFrame({
    "target_price" : original_price
})
subm.to_csv("submission.csv", index = None)